# Site settings
title: Navdeep Singh
header-img: img/new-home-bg.jpg
email: navdeep.singh@publics.com.sg
copyright_name: navdeepsingh.in
description: "Type down my career learnings"
baseurl: ""
url: "http://navdeepsingh.in"
twitter_username: nswebstudio
github_username:  navdeepsingh
facebook_username:  navdeep.er
email_username:  navdeep.singh@publics.com.sg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
