# Site settings
title: Navdeep Singh
header-img: img/website-home-bgd.jpg
email: navdeep.singh@falcon-agency.com
copyright_name: navdeepsingh.in
description: "Jot down my career and life learnings"
baseurl: ""
url: "http://navdeepsingh.in"
twitter_username: nswebstudio
github_username:  navdeepsingh
facebook_username:  navdeep.er
email_username:  navdeep.singh@falcon-agency.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
